### ISSUE TITLE
Maybe Incorrect masking in loss

### ISSUE THREAD

**Issue by feng-yufei** [rishikksh20/SoundStorm-pytorch#4]
Hi Rishikksh20, I found in your soundstorm code some potential bugs, where you only need to calculate loss on masked token of layer q, not all masked tokens in all layers. In my experiment, loss on masked token beyond the current layer results in all noise
https://github.com/rishikksh20/SoundStorm-pytorch/blob/8321c305d2a36647567b397c5bfded8bca4c9e26/SoundStorm.py#L121

Hope you get good results!

**Comment by rishikksh20** [comment]
Hi @feng-yufei I am aware of that, the current branch `update_v2` have not these issues, I am currently working on that branch only, `master` and `update` branches are outdated.

**Comment by rishikksh20** [comment]
@feng-yufei may you review `update_v2` branch,  specifically logic and error calculation part.
